In [ ]:
import torch

# Create a tensor of shape (2, 7)
targets = torch.randn(2, 7)
print(targets)

In [ ]:
# Split the tensor into two sub-tensors along dimension 1
split_tensors = targets.split([1, 1], dim=0)

In [ ]:
# The first sub-tensor will have shape (2, 1)
print(split_tensors[0])
print(split_tensors[0].shape)  # Output: torch.Size([2, 1])

In [ ]:
print(split_tensors[1])
print(split_tensors[1].shape)  # Output: torch.Size([2, 6])

In [ ]:
targets2 = torch.ones(1, 7, 200, 175)


In [ ]:
targets2.size()

In [ ]:
batch_size = targets2.size(0)
batch_size

In [ ]:
image_size = targets2.size(1) * targets2.size(2) # 7 *200 
cls_targets, loc_targets = targets2.split([1, 6], dim=1)

In [ ]:
cls_targets.shape

In [ ]:
cls_targets.sum()

In [ ]:
import torch

# Sample tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

# Create a mask with non-contiguous True values
mask = torch.tensor([[True, False, False], [False, True, False], [True, True, False]])

# Direct indexing
filtered_tensor_direct = tensor[mask] 

# Using torch.masked_select()
filtered_tensor_masked_select = torch.masked_select(tensor, mask) 

print("Direct Indexing:")
print(filtered_tensor_direct)
print(filtered_tensor_direct.shape)

print("\ntorch.masked_select():")
print(filtered_tensor_masked_select)
print(filtered_tensor_masked_select.shape)

Direct Indexing:
tensor([1, 5, 7, 8])
torch.Size([4])

torch.masked_select():
tensor([1, 5, 7, 8])
torch.Size([4])


In [30]:
import torch

x1 = torch.tensor([[1, 2], [3, 4]])
x2 = torch.tensor([1, 2, 3, 4])

In [41]:
x1.shape

torch.Size([2, 2])

In [42]:
torch.unsqueeze(x1, 0)

tensor([[[1, 2],
         [3, 4]]])

In [43]:
torch.unsqueeze(x1, 1)

tensor([[[1, 2]],

        [[3, 4]]])

In [44]:
torch.unsqueeze(x1, 2)

tensor([[[1],
         [2]],

        [[3],
         [4]]])